# Generated by Django 5.1 on 2024-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=100)),
                ("status", models.BooleanField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
